# Generated by Django 2.0.3 on 2018-07-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_signupattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpAttempt',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
