# Generated by Django 2.0.3 on 2018-07-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_forumpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpAttempt',
        ),
    ]
