# Generated by Django 2.0.3 on 2018-07-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_signupattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('verification_code', models.CharField(max_length=100)),
                ('verification_code_email_sent', models.BooleanField()),
            ],
        ),
    ]
